name: rewind
description: A logging tool that enables you to record any data, with full customization of what is captured and the appearance of your logs at every logging level.
version: 0.3.0
repository: https://github.com/mcmah309/anyhow_logging

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  anyhow: ^1.3.1
  rust_core: ^1.0.0
  stack_trace: ^1.11.1
  uuid: ^4.3.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
