name: anyhow_logging
description: Logging utilities for the anyhow package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  anyhow: ^1.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
