name: anyhow_logging
description: Logging utilities for the anyhow package.
version: 0.0.1
repository: https://github.com/mcmah309/anyhow_logging

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  anyhow: ^1.2.1
  stack_trace: ^1.11.1
  uuid: ^4.3.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
